# Generated by Django 2.2.9 on 2020-06-20 18:05

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utc_dt_start', models.DateTimeField()),
                ('naive_dt_start_date', models.DateField(blank=True)),
                ('naive_dt_start_time', models.TimeField(blank=True)),
                ('timezone', models.CharField(max_length=30)),
                ('dt_start_is_included', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq', models.CharField(choices=[(0, 'YEARLY'), (1, 'MONTHLY'), (2, 'WEEKLY'), (3, 'DAILY')], max_length=30, verbose_name='Frequency')),
                ('dtstart', models.DateField(blank=True)),
                ('interval', models.PositiveIntegerField(default=1)),
                ('wkst', models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0, max_length=30, verbose_name='First Weekday')),
                ('bymonth', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=None, max_length=26, null=True)),
                ('bymonthday', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, '1st day'), (2, '2nd day'), (3, '3rd day'), (4, '4th day'), (5, '5th day'), (6, '6th day'), (7, '7th day'), (8, '8th day'), (9, '9th day'), (10, '10th day'), (11, '11th day'), (12, '12th day'), (13, '13th day'), (14, '14th day'), (15, '15th day'), (16, '16th day'), (17, '17th day'), (18, '18th day'), (19, '19th day'), (20, '20th day'), (21, '21st day'), (22, '22nd day'), (23, '23rd day'), (24, '24th day'), (25, '25th day'), (26, '26th day'), (27, '27th day'), (28, '28th day'), (29, '29th day'), (30, '30th day'), (31, '31st day')], default=None, max_length=83, null=True)),
                ('byweekday', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('MO(+1)', 'First Monday'), ('MO(+2)', 'Second Monday'), ('MO(+3)', 'Third Monday'), ('MO(+4)', 'Fourth Monday'), ('MO(+5)', 'Fifth Monday'), ('MO(-1)', 'Last Monday'), ('TU(+1)', 'First Tuesday'), ('TU(+2)', 'Second Tuesday'), ('TU(+3)', 'Third Tuesday'), ('TU(+4)', 'Fourth Tuesday'), ('TU(+5)', 'Fifth Tuesday'), ('TU(-1)', 'Last Tuesday'), ('WE(+1)', 'First Wednesday'), ('WE(+2)', 'Second Wednesday'), ('WE(+3)', 'Third Wednesday'), ('WE(+4)', 'Fourth Wednesday'), ('WE(+5)', 'Fifth Wednesday'), ('WE(-1)', 'Last Wednesday'), ('TH(+1)', 'First Thursday'), ('TH(+2)', 'Second Thursday'), ('TH(+3)', 'Third Thursday'), ('TH(+4)', 'Fourth Thursday'), ('TH(+5)', 'Fifth Thursday'), ('TH(-1)', 'Last Thursday'), ('FR(+1)', 'First Friday'), ('FR(+2)', 'Second Friday'), ('FR(+3)', 'Third Friday'), ('FR(+4)', 'Fourth Friday'), ('FR(+5)', 'Fifth Friday'), ('FR(-1)', 'Last Friday'), ('SA(+1)', 'First Saturday'), ('SA(+2)', 'Second Saturday'), ('SA(+3)', 'Third Saturday'), ('SA(+4)', 'Fourth Saturday'), ('SA(+5)', 'Fifth Saturday'), ('SA(-1)', 'Last Saturday'), ('SU(+1)', 'First Sunday'), ('SU(+2)', 'Second Sunday'), ('SU(+3)', 'Third Sunday'), ('SU(+4)', 'Fourth Sunday'), ('SU(+5)', 'Fifth Sunday'), ('SU(-1)', 'Last Sunday')], default=None, max_length=293, null=True)),
                ('bysetpos', models.IntegerField(blank=True, default=None, null=True)),
                ('count', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('utc_until', models.DateTimeField(blank=True, default=None, null=True)),
                ('naive_until_date', models.DateField(blank=True, default=None, null=True)),
                ('naive_until_time', models.TimeField(blank=True, default=None, null=True)),
                ('exclude', models.BooleanField(default=False)),
                ('recurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', related_query_name='rule', to='djangorrules.Recurrence')),
            ],
        ),
    ]
