# Generated by Django 2.2.9 on 2020-06-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangorrules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='freq',
            field=models.PositiveSmallIntegerField(choices=[(0, 'YEARLY'), (1, 'MONTHLY'), (2, 'WEEKLY'), (3, 'DAILY')], verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='wkst',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0, verbose_name='First Weekday'),
        ),
    ]
