# Generated by Django 2.2.9 on 2020-06-21 05:13

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangorrules', '0003_auto_20200621_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='byweekday',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
