# Generated by Django 2.2.9 on 2020-06-21 06:23

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangorrules', '0004_auto_20200621_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='byweekday',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], default=None, max_length=20, null=True),
        ),
    ]
