# Generated by Django 2.2.9 on 2020-06-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangorrules', '0008_auto_20200623_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='interval',
            field=models.PositiveIntegerField(),
        ),
    ]
