# Generated by Django 2.2.9 on 2020-06-23 16:51

from django.db import migrations, models
import djangorrules.validators


class Migration(migrations.Migration):

    dependencies = [
        ('djangorrules', '0009_auto_20200623_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='interval',
            field=models.PositiveIntegerField(default=None, validators=[djangorrules.validators.validate_nonzero]),
        ),
    ]
