# Generated by Django 2.2.9 on 2020-06-27 17:19

from django.db import migrations, models
import djangorrules.validators


class Migration(migrations.Migration):

    dependencies = [
        ('djangorrules', '0011_auto_20200626_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='interval',
            field=models.PositiveIntegerField(blank=True, default=None, validators=[djangorrules.validators.validate_nonzero]),
        ),
    ]
