# Generated by Django 2.2.9 on 2020-06-28 01:09

from django.db import migrations, models
import djangorrules.validators


class Migration(migrations.Migration):

    dependencies = [
        ('djangorrules', '0012_auto_20200627_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='year_month_mode',
            field=models.CharField(blank=True, choices=[(None, 'Select a mode'), (0, 'by date'), (1, 'by day')], default=None, max_length=30, null=True, verbose_name='mode'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='interval',
            field=models.PositiveIntegerField(default=None, validators=[djangorrules.validators.validate_nonzero]),
        ),
    ]
