# Generated by Django 2.2.9 on 2020-06-28 02:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangorrules', '0014_auto_20200628_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='year_month_mode',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, 'Select a mode'), (1, 'by date'), (2, 'by day')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='mode'),
        ),
    ]
