# Generated by Django 2.2.9 on 2020-07-09 18:50
import pytz
from datetime import datetime, time
from django.db import migrations, models
import django.utils.timezone


def utc_field_default_value(apps, schema):
    Rule = apps.get_model('djangorrules', 'rule')
    RDate = apps.get_model('djangorrules', 'rdate')
    TIME = time(hour=12, minute=0, second=0)

    rules = Rule.objects.all()
    r_dates = RDate.objects.all()
    for rule in rules:
        tzname = rule.recurrence.timezone
        rule.utc_dtstart = tzname.localize(datetime.combine(rule.dtstart, TIME))
        rule.save()

    for r_date in r_dates:
        tzname = r_date.recurrence.timezone
        r_date.utc_dt = tzname.localize(datetime.combine(r_date.naive_dt, TIME))
        r_date.save()


class Migration(migrations.Migration):
    dependencies = [
        ('djangorrules', '0017_auto_20200701_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='naive_until_date',
            new_name='until_date',
        ),
        migrations.RemoveField(
            model_name='rdate',
            name='dt',
        ),
        migrations.RemoveField(
            model_name='rdate',
            name='naive_dt_time',
        ),
        migrations.RemoveField(
            model_name='recurrence',
            name='naive_dt_start_date',
        ),
        migrations.RemoveField(
            model_name='recurrence',
            name='naive_dt_start_time',
        ),
        migrations.RemoveField(
            model_name='recurrence',
            name='utc_dt_start',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='naive_until_time',
        ),
        migrations.AddField(
            model_name='rdate',
            name='utc_dt',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rule',
            name='utc_dtstart',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rdate',
            name='naive_dt',
            field=models.DateField(blank=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='dtstart',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rule',
            name='utc_until',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.RunPython(utc_field_default_value)
    ]
