# Generated by Django 2.2.9 on 2020-07-12 01:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('djangorrules', '0019_auto_20200709_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurrence',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        )
    ]
